---
title: "Descriptive statistics"
author: "Guilhem Huau"
date: "`r format(Sys.time(), '%d/%m/%Y %H:%M:%S')`"
colorlinks: true
output:
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: TRUE
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      include = TRUE,
                      warning = TRUE,
                      message = TRUE,
                      
                      cache = FALSE, # save chunks output 
                      
                      results = "hold", # display chunk output in one block
                      
                      tidy = FALSE, # better code organisation
                      tidy.opts = list(width.cutoff = 80),
                      strip.white = TRUE, #remove the white lines in the beginning or end of a source chunk
                      
                      fig.align = "center",
                      fig.width = 9,
                      fig.height = 5)

knitr::opts_knit$set(progress = TRUE,
                     verbose = FALSE,
                     width = 80)

```

```{css echo=FALSE, eval = TRUE}
/* add some CSS styling here */
```

**Packages / R-options:**
```{r pkgs_options}
suppressPackageStartupMessages({
  require(dplyr)
  require(tibble)
  require(tidyr)
  require(magrittr)
  require(plotly)
})

#  R options
options(stringsAsFactors = FALSE)

```

```{r loading_data}
dat_root = read.csv("E:/SoyBeanData/Phenotype/2017/2017_Tottori_May_RootPhenotype.csv")
dat_shoot = read.csv("E:/SoyBeanData/Phenotype/2017/2017_Tottori_May_ShootPhenotype.csv")
dat_shoot$year = 2017
dat_join = inner_join(dat_shoot, dat_root, by = colnames(dat_root)[1:9])
dat_join$ID = 1:nrow(dat_join)
dat_join$block = as.factor(dat_join$block)
weightProblem = filter(dat_join,LeafWeight_g > TotalWeight_g)
dat_join = anti_join(dat_join, weightProblem)

dat_join = dat_join[,-(c(1:6,8,9))]
nam = names(dat_join)

dat_complete = dat_join[complete.cases(dat_join),]

dat_choose = dat_complete[,c(1:5,9)]
names(dat_choose) = c("block", "PlantHeight","LeafWeight","TotalWeight","TRL","NumTips")
```

***
#General statistics

```{r general, echo=FALSE}
summary(dat_choose)

```

***
# Plant Height Statistics

```{r plantHeight, echo=FALSE}
tapply(dat_choose[,2], dat_choose$block, summary)
plot_ly(dat_choose, x = ~block, y= ~PlantHeight, type = "box")
```

***
# Leaf Weight Statistics

```{r LeafWeight, echo=FALSE}
tapply(dat_choose[,3], dat_choose$block, summary)
plot_ly(dat_choose, x = ~block, y= ~LeafWeight, type = "box")
```

***
# Total Weight Statistics

```{r TotalWeight, echo=FALSE}
tapply(dat_choose[,4], dat_choose$block, summary)
plot_ly(dat_choose, x = ~block, y= ~TotalWeight, type = "box")
```

***
# Total Root Length Statistics

```{r TRL, echo=FALSE, warning=FALSE}
tapply(dat_choose[,5], dat_choose$block, summary)
plot_ly(dat_choose, x = ~block, y= ~TRL, type = "box")
```

***
# Number of Root Tips Statistics

```{r NumTips, echo=FALSE}
tapply(dat_choose[,6], dat_choose$block, summary)
plot_ly(dat_choose, x = ~block, y= ~NumTips, type = "box")
```






# Appendix
```{r sessionInfo}
print(sessionInfo(), locale = FALSE)
```